services:
  postgres:
    container_name: db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=9uN9H9FMyhLtgkLi
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=aliff.ibr@icloud.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "8080:80"
